2022-02-13 13:09:13,946 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:09:13,946 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test1
2022-02-13 13:09:13,947 DEBUG    client.py Сформировано presence сообщение для пользователя test1
2022-02-13 13:09:13,949 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:09:13,949 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,326 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:09:14,326 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test3
2022-02-13 13:09:14,327 DEBUG    client.py Сформировано presence сообщение для пользователя test3
2022-02-13 13:09:14,328 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:09:14,329 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,329 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:09:14,329 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,330 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:09:14,330 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:09:14,330 DEBUG    client.py Запущены процессы
2022-02-13 13:09:14,351 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:09:14,351 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test2
2022-02-13 13:09:14,351 DEBUG    client.py Сформировано presence сообщение для пользователя test2
2022-02-13 13:09:14,351 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:09:14,353 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,353 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,353 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:09:14,353 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:09:14,353 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:09:14,354 DEBUG    client.py Запущены процессы
2022-02-13 13:09:14,860 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:09:14,861 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:09:14,863 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:09:14,863 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:09:14,865 DEBUG    client.py Запущены процессы
2022-02-13 13:26:53,462 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:27:00,450 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: ozzzzz
2022-02-13 13:27:00,451 DEBUG    client.py Сформировано presence сообщение для пользователя ozzzzz
2022-02-13 13:27:00,454 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:27:00,457 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:27:01,007 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:27:01,007 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:27:01,007 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:27:01,007 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:27:01,008 DEBUG    client.py Запущены процессы
2022-02-13 13:27:23,180 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:27:28,203 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: notoz
2022-02-13 13:27:28,204 DEBUG    client.py Сформировано presence сообщение для пользователя notoz
2022-02-13 13:27:28,207 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:27:28,210 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:27:28,745 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:27:28,745 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:27:28,746 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:27:28,746 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:27:28,746 DEBUG    client.py Запущены процессы
2022-02-13 13:28:06,142 CRITICAL client.py Потеряно соединение с сервером.
2022-02-13 13:28:06,142 CRITICAL client.py Потеряно соединение с сервером.
2022-02-13 13:35:05,608 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:35:05,608 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test1
2022-02-13 13:35:05,609 DEBUG    client.py Сформировано presence сообщение для пользователя test1
2022-02-13 13:35:05,610 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:35:05,611 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:35:05,887 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:35:05,888 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test2
2022-02-13 13:35:05,888 DEBUG    client.py Сформировано presence сообщение для пользователя test2
2022-02-13 13:35:05,888 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:35:05,889 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:35:05,920 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:35:05,920 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:35:05,920 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:35:05,921 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:35:05,921 DEBUG    client.py Запущены процессы
2022-02-13 13:35:06,011 DEBUG    decorator.py Была вызвана функция arg_parser(), вызов произошёл из функции main()
2022-02-13 13:35:06,011 INFO     client.py Запущен клиент с парамертами: адрес сервера: 127.0.0.1 , порт: 7777, имя пользователя: test3
2022-02-13 13:35:06,011 DEBUG    client.py Сформировано presence сообщение для пользователя test3
2022-02-13 13:35:06,012 DEBUG    decorator.py Была вызвана функция create_presence(), вызов произошёл из функции main()
2022-02-13 13:35:06,013 DEBUG    decorator.py Была вызвана функция send_message(), вызов произошёл из функции main()
2022-02-13 13:35:06,025 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:35:06,025 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:35:06,026 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:35:06,026 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:35:06,027 DEBUG    client.py Запущены процессы
2022-02-13 13:35:06,570 DEBUG    decorator.py Была вызвана функция get_message(), вызов произошёл из функции main()
2022-02-13 13:35:06,570 DEBUG    client.py Разбор приветственного сообщения от сервера: {'response': 200}
2022-02-13 13:35:06,572 DEBUG    decorator.py Была вызвана функция process_response_ans(), вызов произошёл из функции main()
2022-02-13 13:35:06,573 INFO     client.py Установлено соединение с сервером. Ответ сервера: 200 : OK
2022-02-13 13:35:06,574 DEBUG    client.py Запущены процессы
2022-02-13 13:36:17,417 CRITICAL client.py Потеряно соединение с сервером.
2022-02-13 13:36:17,418 CRITICAL client.py Потеряно соединение с сервером.
2022-02-13 13:36:17,418 CRITICAL client.py Потеряно соединение с сервером.
